context:
  version: "0.2101.3"

package:
  name: architect-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@angular-devkit/architect-cli/-/architect-cli-${{ version }}.tgz
  sha256: 7899e5d57e9ab95679cdbc27dc530f28ae54f7dba05f4f93c804d6a8a4a6f04f

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - architect --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Executable for running an Architect Builder.
  homepage: https://github.com/angular/angular-cli
  repository: https://github.com/angular/angular-cli

extra:
  recipe-maintainers:
    - danielnachun
