context:
  version: "0.2101.5"

package:
  name: architect-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@angular-devkit/architect-cli/-/architect-cli-${{ version }}.tgz
  sha256: 0407e184a6a6c5bb922fedeb62e6637ed647d26e79499eb81f3061fe700f8dbe

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - architect --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Executable for running an Architect Builder.
  homepage: https://github.com/angular/angular-cli
  repository: https://github.com/angular/angular-cli

extra:
  recipe-maintainers:
    - danielnachun
